version: "3.8"
services:
  botapp:
    build: ./
    command: python main.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 12100:12100
  db:
      image: postgres
      env_file:
        - .env.db
      ports:
        - 5434:5432
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U bot"]
        interval: 1s
        timeout: 5s
        retries: 10

volumes:
  db:
